### ISSUE TITLE
Add Python support along with JS support.

### ISSUE THREAD

**Issue by ohxxm** [catppuccin/palette#13]
JavaScript is a great language but NPM has packaging issues at times, mostly with vulnerabilities. Python is another great language which doesn't have these issues. I will be willing to contribute to this to add Python support along with JavaScript support.

**Comment by ohxxm** [comment]
If allowed to start this, I can start development ASAP.

**Comment by unseen-ninja** [comment]
I wanted to answer this a couple days ago but then accidentally marked it as read … sorry. What exactly would you suggest to be implemented in Python? c:
Maybe I'm dumb, but I can't think of a usecase from the top of my head that would require Python. o:

**Comment by ohxxm** [comment]
I wanted the colors to be implemented/ported to the Python language. This makes it easier for people who dev in Python.

**Comment by unseen-ninja** [comment]
Oh sure. I don't think there would be anyone against that. c:

**Comment by ohxxm** [comment]
> Oh sure. I don't think there would be anyone against that. c:

Great, will start working on this asap

**Comment by unseen-ninja** [comment]
Looking forward to how it will turn out. ^—^

**Comment by sgoudham** [comment]
Do you have any further updates on this @Spaxly? Absolutely no worries if there are none. Just wondering what the state of this issue is.

**Comment by ohxxm** [comment]
> Do you have any further updates on this @Spaxly? Absolutely no worries if there are none. Just wondering what the state of this issue is.

Sorry, this had slipped my mind completely, since I'm working on other projects ATM, I will likely not continue this, thought this does not mean I will not come back to it. For now, I will close this issue. Apologies once again.

**Comment by sgoudham** [comment]
Ah, no worries! I actually think it's better to keep the issue open as someone else might come across it and want to try and implement it themselves!

There's absolutely no pressure to try and come back to this!

**Comment by backwardspy** [comment]
i'll pick up the python implementation

**Comment by sgoudham** [comment]
Closing this issue now as [`catppuccin/python`](https://github.com/catppuccin/python) exists!
Thanks to @backwardspy for picking it up and getting this issue closed <3
