### ISSUE TITLE
Seperate projects out to submodules to facilitate better access control

### ISSUE THREAD

**Issue by nyxkrage** [catppuccin/palette#25]
Currently if someone needs to maintain for example the Rust crate, they have to be given access to the entire repo
This is obviously not an ideal situation. A solution to this would be to move each project out into a separate repo and then including them in this repo as a submodules, that way this repo just acts as a sort of hub.

This should probably just be done for future projects being added and perhaps the Rust crate as its still fairly new, as backporting this to the other projects in here, is a pain that probably isn't worth it.

**Comment by sgoudham** [comment]
I'd be really interested in hearing @catppuccin/core's opinions on this, especially because it's one of the _main_ repositories.

I personally agree and it makes sense to do this going forward and not trying to retroactively applying it to everything

**Comment by nekowinston** [comment]
Agreed, this is why I wish GitHub had projects like GitLab.

We can, however, control access with [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) like Monorepos do.

**Comment by nyxkrage** [comment]
Code Owners doesn't restrict permissions but only notifies the owners when someone tries to change the code AFAIK, so I don't think it makes sense in this case

**Comment by unseen-ninja** [comment]
Basically the same question we also try to answer for the Userstyles, right? Personally I think submodules would make a lot of sense, as it's likely the easiest way to achieve proper separation. Codeowners are an alternative worth exploring tho.

**Comment by sgoudham** [comment]
Going forward (rust, python, etc). We decided to separate out these modules into their own repositories (catppuccin/python and catppuccin/rust, etc)
