### ISSUE TITLE
LibreOffice Palette

### ISSUE THREAD

**Issue by enderprism** [catppuccin/palette#55]
Can be taken from [Dracula's LibreOffice palette](https://github.com/dracula/libreoffice).
Ideally, it would have 4 separate palettes, for the 4 catppuccin palettes.

**Comment by sgoudham** [comment]
Hey :wave: 

Please raise a new [Port Discussion](https://github.com/catppuccin/catppuccin/discussions/new?category=port-requests) in catppuccin/catppuccin for new ports.

**Comment by shadow-absorber** [comment]
made a new port discussion here: [https://github.com/catppuccin/catppuccin/discussions/2350](https://github.com/catppuccin/catppuccin/discussions/2350)
