### ISSUE TITLE
Kotlin Version

### ISSUE THREAD

**Issue by lighttigerXIV** [catppuccin/palette#74]
I have a kotlin version of the library. Is it worth it make it official and make a proper readme?
https://github.com/lighttigerXIV/catppuccin-kt

**Comment by sgoudham** [comment]
Hey :wave: 

I've added a comment to our existing [Kotlin](https://github.com/catppuccin/catppuccin/issues/1896#issuecomment-2016530932) issue, which has more details about what we're expecting for code libraries.

Closing this as any further discussion should take place in the issue raised in catppuccin/catppuccin
