### ISSUE TITLE
Include flavour emojis as part of the `palette.json`

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/palette#80]
The following emojis: 🌻, 🪴, 🌺 and 🌿 are tied to **Latte**, **Frappé**, **Macchiato** and **Mocha**. It'd be nice to ship them as part of the `palette.json` so we can pull them into the language libraries and whiskers. 

Mostly raising this because I've seen the following whiskers v2 code in [dark-reader](https://github.com/catppuccin/dark-reader/blob/560b302f12d402bd9966d177a023c0659c674a68/dark-reader.tera#L36-L44) and [github-readme-stats](https://github.com/catppuccin/github-readme-stats/blob/fbc2a23e41eefb1cb9c0ee760bb65f3a361e415b/github-readme-stats.tera#L30-L37):

```jinja
{% for id, flavor in flavors %}
<details>
{%- if id == "latte" %}
<summary>🌻 Latte</summary>
{%- elif id == "frappe" %}
<summary>🪴 Frappé</summary>
{%- elif id == "macchiato" %}
<summary>🌺 Macchiato</summary>
{%- else %}
<summary>🌿 Mocha</summary>
{%- endif %}
...
```

And it'd be nice to reduce that into:

```jinja
{% for id, flavor in flavors %}
<details>
<summary>{{flavor.emoji}} {{flavor.name}}</summary>
...
```

**Comment by uncenter** [comment]
The pattern you mentioned is also used in https://github.com/catppuccin/fzf. I'll make PRs at the three mentioned repositories if #81 gets merged and released :)
